const fs = require('fs');

const words = [
    { word: "curler", synonym: "roller" },
    { word: "grasping", synonym: "greedy" },
    { word: "skull", synonym: "cranium" },
    { word: "conscientious", synonym: "virtuous" },
    { word: "hate", synonym: "loathe" },
    { word: "foyer", synonym: "lobby" },
    { word: "maneuver", synonym: "manipulate" },
    { word: "numerous", synonym: "many" },
    { word: "wonderful", synonym: "marvelous" },
    { word: "bloodbath", synonym: "massacre" },
    { word: "cruel", synonym: "mean" },
    { word: "important", synonym: "meaningful" },
    { word: "quite", synonym: "fairly" },
    { word: "in the meantime", synonym: "meanwhile" },
    { word: "reminiscence", synonym: "memory" },
    { word: "obligatory", synonym: "compulsory" },
    { word: "unforeseen", synonym: "unexpected" },
    { word: "after", synonym: "following, next" },
    { word: "intellectual", synonym: "mental" },
    { word: "contemporary", synonym: "modern" },
    { word: "humble", synonym: "modest" },
    { word: "religious", synonym: "devout" },
    { word: "impolite", synonym: "rude" },
    { word: "second", synonym: "moment" },
    { word: "temper", synonym: "mood" },
    { word: "immobile", synonym: "motionless" },
    { word: "mobile", synonym: "moveable" },
    { word: "hearsay", synonym: "rumor" },
    { word: "pattern", synonym: "sample" },
    { word: "homicide", synonym: "murder" },
    { word: "incidentally", synonym: "by the way" },
    { word: "to condemn", synonym: "to sentence" },
    { word: "devil", synonym: "satan" },
    { word: "passable", synonym: "satisfactory" },
    { word: "contented", synonym: "satisfied" },
    { word: "warranty", synonym: "guarantee" },
    { word: "meager", synonym: "scanty" },
    { word: "almost", synonym: "nearly" },
    { word: "afraid", synonym: "scared" },
    { word: "dull", synonym: "blunt" },
    { word: "comic", synonym: "comedian" },
    { word: "stupid", synonym: "silly" },
    { word: "to renew", synonym: "to resume" },
    { word: "hint", synonym: "trace, tip" },
    { word: "uncared for", synonym: "neglected" },
    { word: "damage", synonym: "hurt" },
    { word: "easy", synonym: "simple" },
    { word: "transparent", synonym: "obvious" },
    { word: "moment", synonym: "occasion" },
    { word: "to beat", synonym: "to defeat" },
    { word: "unbiased", synonym: "impartial" },
    { word: "rude", synonym: "impolite" },
    { word: "deserted", synonym: "abandoned" },
    { word: "to denote", synonym: "to indicate, to represent" },
    { word: "unmarried", synonym: "single" },
    { word: "cry", synonym: "sob" },
    { word: "foxy", synonym: "cunning" },
    { word: "depraved", synonym: "wicked, evil" },
    { word: "ability", synonym: "skill" },
    { word: "scrumptious", synonym: "delicious" },
    { word: "mysterious", synonym: "occult" },
    { word: "couch", synonym: "sofa" },
    { word: "vacancy", synonym: "emptiness" },
    { word: "special", synonym: "exceptional" },
    { word: "daybreak", synonym: "dawn" },
    { word: "trivial", synonym: "worthless" },
    { word: "naked", synonym: "bare" },
    { word: "to bring sth. back", synonym: "to reintroduce" },
    { word: "arise", synonym: "occur" },
    { word: "convention", synonym: "conference" },
    { word: "uninjured", synonym: "unhurt" },
    { word: "mild", synonym: "gentle" },
    { word: "earth", synonym: "soil" },
    { word: "movie", synonym: "film" },
    { word: "beneficial", synonym: "favorable" },
    { word: "to illustrate", synonym: "to demonstrate" },
    { word: "to hazard", synonym: "to endanger" },
    { word: "worn", synonym: "old" },
    { word: "everlasting", synonym: "eternal" },
    { word: "enemy", synonym: "opponent" },
    { word: "modern", synonym: "contemporary" },
    { word: "uncommon", synonym: "unusual" },
    { word: "non - stop", synonym: "non-stop" },
    { word: "pressing", synonym: "urgent" },
    { word: "amateur", synonym: "beginner" },
    { word: "to narrate", synonym: "to relate" },
    { word: "possibility", synonym: "opportunity" },
    { word: "abandon", synonym: "forsake" },
    { word: "contrary", synonym: "opposite" },
    { word: "famous", synonym: "famed, renowned" },
    { word: "militant", synonym: "combative" },
    { word: "poisonous", synonym: "toxic" },
    { word: "dirty", synonym: "soiled" },
    { word: "help", synonym: "aid" },
    { word: "to intend", synonym: "to mean" },
    { word: "association", synonym: "organization" },
    { word: "continue", synonym: "persist" },
    { word: "branch", synonym: "department" },
    { word: "fool", synonym: "idiot" },
    { word: "particular", synonym: "specific" },
    { word: "upset", synonym: "perturb" },
    { word: "inventory", synonym: "stock" },
    { word: "independent", synonym: "autonomous" },
    { word: "to bring sb. up", synonym: "to raise" },
    { word: "conservative", synonym: "cautious" },
    { word: "to oversee", synonym: "to supervise" },
    { word: "surplus", synonym: "excess" },
    { word: "decontrol", synonym: "deregulate" },
    { word: "nervous", synonym: "perturbed" },
    { word: "choosy", synonym: "picky" },
    { word: "midway", synonym: "halfway" },
    { word: "deliberate", synonym: "planned" },
    { word: "fantastic", synonym: "great, brilliant" },
    { word: "impatient", synonym: "eager" },
    { word: "believable", synonym: "plausible" },
    { word: "omnipotent", synonym: "all" },
    { word: "to imitate", synonym: "to mimic" },
    { word: "belly", synonym: "stomach" },
    { word: "nice", synonym: "pleasing" },
    { word: "gratis", synonym: "free of charge" },
    { word: "well mannered", synonym: "polite" },
    { word: "able", synonym: "capable" },
    { word: "to glitter", synonym: "to sparkle" },
    { word: "ballot", synonym: "poll" },
    { word: "formerly", synonym: "previously" },
    { word: "new", synonym: "fresh" },
    { word: "precept", synonym: "principle" },
    { word: "approve", synonym: "endorse" },
    { word: "before", synonym: "prior" },
    { word: "fanatic", synonym: "enthusiast" },
    { word: "precedence", synonym: "priority" },
    { word: "yield", synonym: "produce" },
    { word: "economic", synonym: "profitable" },
    { word: "suggest", synonym: "propose" },
    { word: "inheritor", synonym: "heir" },
    { word: "unusual", synonym: "strange" },
    { word: "impasse", synonym: "deadlock" },
    { word: "thrive", synonym: "prosper" },
    { word: "successful", synonym: "prosperous" },
    { word: "hypothesis", synonym: "speculation" },
    { word: "hard", synonym: "firm" },
    { word: "backbone", synonym: "spine" },
    { word: "constitution", synonym: "structure" },
    { word: "sunrise", synonym: "dawn" },
    { word: "valueless", synonym: "worthless" },
    { word: "awful", synonym: "atrocious" },
    { word: "to demonstrate", synonym: "to protest" },
    { word: "adult", synonym: "grown" },
    { word: "measure", synonym: "degree" },
    { word: "divide", synonym: "split" },
    { word: "manmade", synonym: "artificial" },
    { word: "to put sth. back", synonym: "to postpone" },
    { word: "cussed", synonym: "stubborn" },
    { word: "loveable", synonym: "habitable" },
    { word: "obdurate", synonym: "stubborn" },
    { word: "intermittent", synonym: "sporadic" },
    { word: "drastic", synonym: "extreme" },
    { word: "moreover", synonym: "in addition" },
    { word: "detached", synonym: "indifferent" },
    { word: "immaculate", synonym: "spotless" },
    { word: "dedicated", synonym: "committed" },
    { word: "ignorant", synonym: "unaware" },
    { word: "constant", synonym: "fixed" },
    { word: "intolerant", synonym: "bigoted" },
    { word: "congested", synonym: "stuffed" },
    { word: "to symbolize", synonym: "to represent" },
    { word: "dash", synonym: "sprint" },
    { word: "hunger", synonym: "starvation" },
    { word: "stable", synonym: "steady" },
    { word: "egocentric", synonym: "selfish" },
    { word: "hospitable", synonym: "cordial" },
    { word: "legitimate", synonym: "valid, leva" },
    { word: "mindless", synonym: "senseless" },
    { word: "destiny", synonym: "fate" },
    { word: "touchy", synonym: "sensitive" },
    { word: "loopy", synonym: "crazy" },
    { word: "imperative", synonym: "vital" },
    { word: "business", synonym: "commerce, trade" },
    { word: "honest", synonym: "truthful" },
    { word: "napkin", synonym: "serviette" },
    { word: "disgrace", synonym: "shame" },
    { word: "confederate", synonym: "accomplice" },
    { word: "to enquire", synonym: "to investigate" },
    { word: "sure", synonym: "certain" },
    { word: "to provide", synonym: "to supply" },
    { word: "phantasm", synonym: "illusion" },
    { word: "scarcity", synonym: "shortage" },
    { word: "delicate", synonym: "fragile" },
    { word: "dull (person)", synonym: "stupid" },
    { word: "dawn", synonym: "daybreak" },
    { word: "about", synonym: "approximately" },
    { word: "to hawk", synonym: "to peddle" },
    { word: "constantly", synonym: "always" },
    { word: "to overlook", synonym: "to miss" },
    { word: "barren", synonym: "infertile" },
    { word: "merciless", synonym: "cruel" },
    { word: "bizarre", synonym: "weird" },
    { word: "continuous", synonym: "continual" },
    { word: "maximum", synonym: "uppermost" },
    { word: "bum", synonym: "backside, behind, bottom" },
    { word: "to mirror", synonym: "to reflect" },
    { word: "commencement", synonym: "graduation" },
    { word: "dumb", synonym: "stupid" },
    { word: "usually", synonym: "generally, normally" },
    { word: "becoming", synonym: "fitting" },
    { word: "concord", synonym: "harmony" },
    { word: "always", synonym: "forever" },
    { word: "bashful", synonym: "shy" },
    { word: "soiled", synonym: "dirty" },
    { word: "daring", synonym: "bold" },
    { word: "to expire", synonym: "to run out" },
    { word: "insufficient", synonym: "inadequate" },
    { word: "signal", synonym: "sign" },
    { word: "foolish", synonym: "silly" },
    { word: "candy", synonym: "sweet" },
    { word: "happily", synonym: "fortunately" },
    { word: "word", synonym: "synonym" },
    { word: "inflow", synonym: "influx" },
    { word: "surroundings", synonym: "environment" },
    { word: "tailored", synonym: "tailor" },
    { word: "impassive", synonym: "emotionless" },
    { word: "docile", synonym: "tame" },
    { word: "transitory", synonym: "temporary" },
    { word: "internal", synonym: "inner" },
    { word: "a narrative", synonym: "a story" },
    { word: "to mimic", synonym: "to imitate" },
    { word: "gay", synonym: "homosexual" },
    { word: "bid", synonym: "tender" },
    { word: "organic", synonym: "biological" },
    { word: "to confine", synonym: "to restrict" },
    { word: "convenient", synonym: "handy" },
    { word: "to migrate", synonym: "emigrate" },
    { word: "blameless", synonym: "innocent" },
    { word: "crazy", synonym: "insane" },
    { word: "noted", synonym: "famous" },
    { word: "madness", synonym: "insanity" },
    { word: "arrogant", synonym: "haughty" },
    { word: "awful", synonym: "terrible" },
    { word: "to disclaim", synonym: "to deny" },
    { word: "to vary", synonym: "to differ" },
    { word: "accurate", synonym: "correct" },
    { word: "sacristy", synonym: "vestry" },
    { word: "dreadful", synonym: "terrible" },
    { word: "immoderate", synonym: "excessive" },
    { word: "cozy", synonym: "comfortable" },
    { word: "garbage can", synonym: "trashcan" },
    { word: "perception", synonym: "insight" },
    { word: "hang", synonym: "out" },
    { word: "immediate", synonym: "instant" },
    { word: "mind", synonym: "intellect" },
    { word: "vague", synonym: "indistinct" },
    { word: "understandable", synonym: "comprehensible" },
    { word: "indisputable", synonym: "undeniable" },
    { word: "terror", synonym: "terrorism" },
    { word: "highbrow", synonym: "intellectual" },
    { word: "cube", synonym: "dice" },
    { word: "remoted", synonym: "isolated" },
    { word: "well timed", synonym: "timely" },
    { word: "gratuity", synonym: "tip" },
    { word: "disadvantaged", synonym: "deprived" },
    { word: "abundant", synonym: "ample" },
    { word: "to misconceive", synonym: "to misunderstand" },
    { word: "denims", synonym: "jeans" },
    { word: "connect", synonym: "join" },
    { word: "ecstasy", synonym: "joy" },
    { word: "magistrate", synonym: "justice of the peace" },
    { word: "eager", synonym: "keen" },
    { word: "wise", synonym: "knowing" },
    { word: "crusade", synonym: "campaign" },
    { word: "to establish", synonym: "to set up" },
    { word: "neutral", synonym: "impartial" },
    { word: "vicious", synonym: "ferocious" },
    { word: "interplay", synonym: "interaction" },
    { word: "to desert", synonym: "to abandon" },
    { word: "touchdown", synonym: "landing" },
    { word: "oblique", synonym: "indirect" },
    { word: "to accomplish", synonym: "to achieve" },
    { word: "hashish", synonym: "cannabis" },
    { word: "to close", synonym: "to shut" },
    { word: "defective", synonym: "faulty" },
    { word: "mischievous", synonym: "impish" },
    { word: "dormant", synonym: "inactive" },
    { word: "idle", synonym: "lazy" },
    { word: "turbulent", synonym: "blustering" },
    { word: "to disclose", synonym: "to reveal" },
    { word: "dally", synonym: "loiter" },
    { word: "isolated", synonym: "lonely" },
    { word: "missing", synonym: "lost" },
    { word: "drab", synonym: "dull" },
    { word: "fortunate", synonym: "lucky" },
    { word: "off", synonym: "season" },
    { word: "mendacity", synonym: "lying" },
    { word: "superb", synonym: "magnificent" },
    { word: "leading", synonym: "main" },
    { word: "chiefly", synonym: "mainly" },
    { word: "aggressive", synonym: "militant" },
    { word: "noon", synonym: "midday" },
    { word: "vague", synonym: "indistinct" },
    { word: "misfortune", synonym: "mishap" },
    { word: "misread", synonym: "misinterpret" },
    { word: "deceptive", synonym: "misleading" },
    { word: "lacking", synonym: "missing" },
    { word: "jealous", synonym: "envious" },
    { word: "doubt", synonym: "mistrust" },
    { word: "wrong", synonym: "mistaken" },
    { word: "away", synonym: "absent" },
    { word: "to notify", synonym: "to inform" },
    { word: "mannequin", synonym: "model" },
    { word: "dicey", synonym: "risky" },
    { word: "empty", synonym: "drain" },
    { word: "misery", synonym: "distress" },
    { word: "impartial", synonym: "neutral" },
    { word: "to behave", synonym: "to act" },
    { word: "bendy", synonym: "flexible" },
    { word: "extra", synonym: "additional" },
    { word: "to administer", synonym: "to manage" },
    { word: "murderer", synonym: "assassin" },
    { word: "to maintain", synonym: "to preserve" },
    { word: "mediocre", synonym: "fair" },
    { word: "aromatic", synonym: "fragrant" },
    { word: "dispute", synonym: "debate" },
    { word: "ambitious", synonym: "aspiring" },
    { word: "to foretell", synonym: "to predict" },
    { word: "to ignore", synonym: "to disregard" },
    { word: "virtue", synonym: "advantage" },
    { word: "to cope", synonym: "to manage" },
    { word: "appreciable", synonym: "considerable" },
    { word: "disagreeable", synonym: "unpleasant" },
    { word: "rubbish", synonym: "nonsense" },
    { word: "to bear on sth.", synonym: "to affect" },
    { word: "lousy", synonym: "awful" },
    { word: "to consult", synonym: "to refer to" },
    { word: "cranky", synonym: "cross" },
    { word: "mackintosh", synonym: "waterproof coat" },
    { word: "pocket book", synonym: "notebook" },
    { word: "middleman", synonym: "intermediary" },
    { word: "paper money", synonym: "notes" },
    { word: "infamous", synonym: "notorious" },
    { word: "mirth", synonym: "fun" },
    { word: "selection", synonym: "choice" },
    { word: "to quake", synonym: "to tremble" },
    { word: "today", synonym: "nowadays" },
    { word: "self", synonym: "assured" },
    { word: "mean", synonym: "unkind" },
    { word: "contaminate", synonym: "defile" },
    { word: "impediment", synonym: "obstacle" },
    { word: "construction (lit.)", synonym: "interpretation" },
    { word: "hostile", synonym: "antagonistic" },
    { word: "to function", synonym: "to operate" },
    { word: "apparent", synonym: "obvious" },
    { word: "comfort", synonym: "consolation" },
    { word: "unstated", synonym: "unspoken" },
    { word: "enormous", synonym: "huge, immense" },
    { word: "sincere", synonym: "honest" },
    { word: "imperfect", synonym: "faulty" },
    { word: "obsolete", synonym: "out of date" },
    { word: "above", synonym: "overhead" },
    { word: "total", synonym: "entire" },
    { word: "twosome", synonym: "pair" },
    { word: "especially", synonym: "particularly" },
    { word: "monotonous", synonym: "bororing" },
    { word: "to hurry", synonym: "to rush" },
    { word: "ardor", synonym: "passion" },
    { word: "gut", synonym: "intestine" },
    { word: "identical", synonym: "duplicate" },
    { word: "immodest", synonym: "conceited" },
    { word: "untrue", synonym: "unfaithful" },
    { word: "achieve", synonym: "accomplish" },
    { word: "to annoy", synonym: "to irritate, to bother" },
    { word: "awkward", synonym: "clumsy" },
    { word: "completely", synonym: "totally" },
    { word: "post", synonym: "mortem" },
    { word: "to elevate", synonym: "to raise, to promote" },
    { word: "insolvent", synonym: "bankrupt" },
    { word: "to rue", synonym: "to regret" },
    { word: "essential", synonym: "fundamental" },
    { word: "peaceable", synonym: "peaceful" },
    { word: "nightfall", synonym: "dusk" },
    { word: "handsome", synonym: "good" },
    { word: "stupid", synonym: "dense" },
    { word: "zenith", synonym: "peak" },
    { word: "vacant", synonym: "empty" },
    { word: "fragrance", synonym: "perfume" },
    { word: "maybe", synonym: "perhaps, possibly" },
    { word: "aid", synonym: "help, assist" },
    { word: "bad (not good)", synonym: "poor, naughty" },
    { word: "magician", synonym: "conjuror" },
    { word: "unfortunate", synonym: "unlucky" },
    { word: "gravestone", synonym: "headstone" },
    { word: "housebreaking", synonym: "burglary" },
    { word: "to grab", synonym: "to seize" },
    { word: "refrain", synonym: "chorus" },
    { word: "to disappear", synonym: "to vanish" },
    { word: "painting", synonym: "portray" },
    { word: "adjourn", synonym: "postpone" },
    { word: "instructions", synonym: "directions" },
    { word: "momentous", synonym: "powerful" },
    { word: "priority", synonym: "precedence" },
    { word: "stationary", synonym: "fixed" },
    { word: "praise", synonym: "compliment" },
    { word: "insufferable", synonym: "unbearable" },
    { word: "previous", synonym: "preceding" },
    { word: "exactly", synonym: "precisely" },
    { word: "mistrust", synonym: "distrust" },
    { word: "early", synonym: "premature" },
    { word: "untimely", synonym: "premature" },
    { word: "antagonize", synonym: "provoke" },
    { word: "citation", synonym: "quotation" },
    { word: "naughty", synonym: "disobedient" },
    { word: "cheesy", synonym: "corny, tacky" },
    { word: "huge", synonym: "vast" },
    { word: "hole", synonym: "gap" },
    { word: "magnify", synonym: "expand" },
    { word: "lethal", synonym: "deadly" },
    { word: "immune", synonym: "exempt" },
    { word: "mourn", synonym: "grieve" },
    { word: "ban", synonym: "forbid" },
    { word: "infrequent", synonym: "rare" },
    { word: "spontaneous", synonym: "automatic" },
    { word: "to cite", synonym: "to quote" },
    { word: "uncooked", synonym: "raw" },
    { word: "arrive", synonym: "reach, come" },
    { word: "dark", synonym: "dismal" },
    { word: "unlawful", synonym: "illegal" },
    { word: "knowingly", synonym: "deliberately" },
    { word: "moderately", synonym: "reasonably" },
    { word: "insurgent", synonym: "rebel" },
    { word: "uprising", synonym: "rebellion" },
    { word: "clerk", synonym: "receptionist" },
    { word: "miserable", synonym: "depressing" },
    { word: "curative", synonym: "healing" },
    { word: "equity", synonym: "fairness" },
    { word: "immature", synonym: "inexperienced" },
    { word: "artful", synonym: "crafty" },
    { word: "practically", synonym: "virtually" },
    { word: "conscious", synonym: "aware" },
    { word: "to arrive", synonym: "to reach" },
    { word: "apparent", synonym: "evident" },
    { word: "crook", synonym: "criminal" },
    { word: "unvoiced", synonym: "voiceless" },
    { word: "negligent", synonym: "inattentive" },
    { word: "to differentiate", synonym: "to distinguish" },
    { word: "inferior", synonym: "substandard" },
    { word: "win", synonym: "succeed" },
    { word: "hold", synonym: "grasp" },
    { word: "to nominate", synonym: "to appoint" },
    { word: "to near", synonym: "to approach" },
    { word: "to impact", synonym: "to affect" },
    { word: "charter", synonym: "constitution" },
    { word: "eccentric", synonym: "unusual" },
    { word: "consecutive", synonym: "successive" },
    { word: "morose", synonym: "sullen" },
    { word: "disagree", synonym: "differ" },
    { word: "invoice", synonym: "bill" },
    { word: "to withstand", synonym: "to resist" },
    { word: "insupportable", synonym: "intolerable" },
    { word: "meeting", synonym: "assembly" },
    { word: "to convey", synonym: "to communicate" },
    { word: "to denationalize", synonym: "to privatize" },
    { word: "abstract", synonym: "summary" },
    { word: "attractive", synonym: "appealing" },
    { word: "illiberal", synonym: "intolerant" },
    { word: "to overhaul", synonym: "to overtake" },
    { word: "anyway", synonym: "besides" },
    { word: "to respond", synonym: "to reply" },
    { word: "precis", synonym: "summary" },
    { word: "dry", synonym: "arid" },
    { word: "to minimize", synonym: "to play down" },
    { word: "satisfied", synonym: "convinced" },
    { word: "vain", synonym: "useless" },
    { word: "to conform", synonym: "to comply" },
    { word: "conflict", synonym: "clash" },
    { word: "twister", synonym: "tornado" },
    { word: "to float", synonym: "to drift" },
    { word: "instinct", synonym: "intuition" },
    { word: "to admit", synonym: "to confess" },
    { word: "to intensify", synonym: "to heighten" },
    { word: "intriguing", synonym: "fascinating" },
    { word: "moderate", synonym: "lenient" },
    { word: "minor", synonym: "lesser" },
    { word: "to infect", synonym: "to contaminate" },
    { word: "to vacuum", synonym: "to hoover" },
    { word: "removable", synonym: "detachable" },
    { word: "sundown", synonym: "sunset" },
    { word: "joy", synonym: "delight" },
    { word: "encourage", synonym: "support" },
    { word: "class", synonym: "lesson, course" },
    { word: "to vanquish", synonym: "to conquer" },
    { word: "turmoil", synonym: "disturbance" },
    { word: "to transform", synonym: "to convert" },
    { word: "to deprave", synonym: "to corrupt" },
    { word: "to chop", synonym: "to cut" },
    { word: "to diminish", synonym: "to decrease" },
    { word: "to involve", synonym: "to entail" },
    { word: "to magnify", synonym: "to exaggerate" },
    { word: "constancy", synonym: "fidelity" },
    { word: "ornament", synonym: "decoration" },
    { word: "diminish", synonym: "curtail" },
    { word: "nugatory", synonym: "worthless" },
    { word: "revolting", synonym: "disgusting" },
    { word: "torpid", synonym: "lethargic" },
    { word: "prompt", synonym: "immediate" },
    { word: "to operate", synonym: "to function" },
    { word: "vast", synonym: "huge" },
    { word: "to hand sth. out", synonym: "to distribute" },
    { word: "to inspect", synonym: "to examine" },
    { word: "to collect", synonym: "to gather" },
    { word: "impetuous", synonym: "reckless" },
    { word: "to receive", synonym: "to get" },
    { word: "beneficent", synonym: "generous" },
    { word: "nameless", synonym: "anonymous" },
    { word: "to confuse", synonym: "to mix up" },
    { word: "overseas", synonym: "abroad" },
    { word: "to deduce", synonym: "to infer" },
    { word: "high", synonym: "elevated" },
    { word: "convalesce", synonym: "recover" },
    { word: "outside", synonym: "external" },
    { word: "to renounce", synonym: "to give up" },
    { word: "more and more", synonym: "increasingly" },
    { word: "to grouse", synonym: "to grumble" },
    { word: "to assure", synonym: "to guarantee" },
    { word: "advocate", synonym: "support" },
    { word: "coiffure", synonym: "hairstyle" },
    { word: "forehead", synonym: "brow" },
    { word: "discount", synonym: "reduction" },
    { word: "to appear", synonym: "to seem" },
    { word: "except", synonym: "apart from" },
    { word: "to survive", synonym: "to outlive" },
    { word: "migrant", synonym: "drifting" },
    { word: "dead", synonym: "lifeless" },
    { word: "notwithstanding", synonym: "however" },
    { word: "a native", synonym: "a local" },
    { word: "to visualize", synonym: "to imagine" },
    { word: "informal", synonym: "casual" },
    { word: "to begin", synonym: "to start" },
    { word: "infuriate", synonym: "enrage" },
    { word: "animated", synonym: "lively" },
    { word: "chorus", synonym: "refrain" },
    { word: "necessary", synonym: "essential" },
    { word: "provided", synonym: "if" },
    { word: "remorse", synonym: "regret" },
    { word: "domesticate", synonym: "cultivate" },
    { word: "steady", synonym: "regular" },
    { word: "testament", synonym: "testimony" },
    { word: "if", synonym: "whether" },
    { word: "applicable", synonym: "relevant" },
    { word: "difficult", synonym: "hard" },
    { word: "trustworthy", synonym: "reliable" },
    { word: "mend", synonym: "repair" },
    { word: "moral", synonym: "ethical" },
    { word: "nobility", synonym: "the aristocracy" },
    { word: "repute", synonym: "reputation" },
    { word: "abbreviate", synonym: "condense" },
    { word: "unhurt", synonym: "unharmed" },
    { word: "imperative", synonym: "crucial" },
    { word: "dilute", synonym: "weaken, thin" },
    { word: "prosperous", synonym: "affluent" },
    { word: "to fabricate", synonym: "to manufacture" },
    { word: "reasonable", synonym: "fair" },
    { word: "idler", synonym: "loafer" },
    { word: "mandatory", synonym: "required" },
    { word: "suppress", synonym: "restrain" },
    { word: "dossier", synonym: "file" },
    { word: "lucid", synonym: "clear" },
    { word: "complete", synonym: "total" },
    { word: "diverse", synonym: "distinct" },
    { word: "backside", synonym: "behind, bottom" },
    { word: "to answer", synonym: "to reply" },
    { word: "home", synonym: "domestic" },
    { word: "matters", synonym: "things" },
    { word: "correct", synonym: "right" },
    { word: "brow", synonym: "forehead" },
    { word: "remainder", synonym: "the rest" },
    { word: "object", synonym: "thing" },
    { word: "hermetic", synonym: "airtight" },
    { word: "to learn", synonym: "to memorize" },
    { word: "considerate", synonym: "thoughtful" },
    { word: "urgent", synonym: "important" },
    { word: "inconsiderate", synonym: "thoughtless" },
    { word: "silly", synonym: "foolish" },
    { word: "neat", synonym: "tidy" },
    { word: "to evaluate", synonym: "to assess" },
    { word: "substantially", synonym: "considerably" },
    { word: "dangerous", synonym: "unsafe" },
    { word: "to connect", synonym: "to associate, to put through (telephone)" },
    { word: "hall", synonym: "corridor" },
    { word: "french dressing", synonym: "vinaigrette" },
    { word: "to explode", synonym: "to blow up" },
    { word: "to collapse", synonym: "to break down" },
    { word: "to accumulate", synonym: "to build up" },
    { word: "livid", synonym: "furious" },
    { word: "remark", synonym: "comment" },
    { word: "vibrate", synonym: "tremble" },
    { word: "to bring sth. on", synonym: "to cause" },
    { word: "inflexible", synonym: "rigid" },
    { word: "to select", synonym: "to choose" },
    { word: "spotlight", synonym: "highlight" },
    { word: "to illuminate", synonym: "to clarify; to light up" },
    { word: "disaster", synonym: "catastrophe" },
    { word: "to encounter", synonym: "to come across" },
    { word: "to emphasize", synonym: "to stress" },
    { word: "innocent", synonym: "harmless" },
    { word: "undeniable", synonym: "indisputable" },
    { word: "humiliate", synonym: "embarrass" },
    { word: "beautiful", synonym: "attractive" },
    { word: "to impeach", synonym: "to question" },
    { word: "bloodless", synonym: "cold" },
    { word: "hard", synonym: "tough" },
    { word: "dubious", synonym: "doubtful" },
    { word: "reliable", synonym: "dependable" },
    { word: "material", synonym: "fabric" },
    { word: "infantile", synonym: "childish" },
    { word: "to imagine", synonym: "to suppose, to assume" },
    { word: "clever", synonym: "intelligent" },
    { word: "deliberately", synonym: "intentionally" },
    { word: "last", synonym: "final" },
    { word: "brave", synonym: "courageous" },
    { word: "winery", synonym: "vineyard" },
];

fs.writeFileSync('temp_ielts.json', JSON.stringify(words, null, 2));
